export type PlayerRole = "WK" | "BAT" | "AR" | "BOWL";

export interface IplPlayerSeed {
  externalPlayerId: number;
  name: string;
  role: PlayerRole;
  teamCode: string;
  teamName: string;
  status: "active";
  fantasyPoints: number;
  isOverseas: boolean;
  salary: number;
  sourceUrl: string;
}

function makeTeam(teamCode: string, teamName: string, squadPath: string) {
  return (externalPlayerId: number, name: string, role: PlayerRole, isOverseas = false, salary = 8.0): IplPlayerSeed => ({
    externalPlayerId,
    name,
    role,
    teamCode,
    teamName,
    status: "active",
    fantasyPoints: 0,
    isOverseas,
    salary,
    sourceUrl: `https://www.iplt20.com${squadPath}`
  });
}

const csk = makeTeam("CSK", "Chennai Super Kings", "/teams/chennai-super-kings/squad");
const dc = makeTeam("DC", "Delhi Capitals", "/teams/delhi-capitals/squad");
const gt = makeTeam("GT", "Gujarat Titans", "/teams/gujarat-titans/squad");
const kkr = makeTeam("KKR", "Kolkata Knight Riders", "/teams/kolkata-knight-riders/squad");
const lsg = makeTeam("LSG", "Lucknow Super Giants", "/teams/lucknow-super-giants/squad");
const mi = makeTeam("MI", "Mumbai Indians", "/teams/mumbai-indians/squad");
const pbks = makeTeam("PBKS", "Punjab Kings", "/teams/punjab-kings/squad");
const rr = makeTeam("RR", "Rajasthan Royals", "/teams/rajasthan-royals/squad");
const rcb = makeTeam("RCB", "Royal Challengers Bengaluru", "/teams/royal-challengers-bengaluru/squad");
const srh = makeTeam("SRH", "Sunrisers Hyderabad", "/teams/sunrisers-hyderabad/squad");

export const IPL_2026_ROSTER: IplPlayerSeed[] = [
  // ── Chennai Super Kings ──────────────────────────────────────────────────
  csk(5443, "Ruturaj Gaikwad", "BAT", false, 10),
  csk(1, "MS Dhoni", "WK", false, 8.5),
  csk(258, "Sanju Samson", "WK"),
  csk(20593, "Dewald Brevis", "BAT", true),
  csk(22377, "Ayush Mhatre", "BAT"),
  csk(23012, "Kartik Sharma", "WK"),
  csk(1564, "Sarfaraz Khan", "BAT"),
  csk(5653, "Urvil Patel", "WK"),
  csk(20702, "Anshul Kamboj", "AR"),
  csk(22109, "Jamie Overton", "AR", true),
  csk(22153, "Ramakrishna Ghosh", "AR"),
  csk(23008, "Prashant Veer", "AR"),
  csk(2032, "Matthew William Short", "AR", true),
  csk(20581, "Aman Khan", "AR"),
  csk(23022, "Zak Foulkes", "AR", true),
  csk(5431, "Shivam Dube", "AR"),
  csk(2964, "Khaleel Ahmed", "BOWL"),
  csk(20590, "Noor Ahmad", "BOWL", true),
  csk(20575, "Mukesh Choudhary", "BOWL"),
  csk(17118, "Nathan Ellis", "BOWL", true),
  csk(20696, "Shreyas Gopal", "BOWL"),
  csk(22032, "Gurjapneet Singh", "BOWL"),
  csk(5608, "Akeal Hosein", "BOWL", true),
  csk(1505, "Matt Henry", "BOWL", true),
  csk(3763, "Rahul Chahar", "BOWL"),

  // ── Delhi Capitals ───────────────────────────────────────────────────────
  dc(1125, "KL Rahul", "WK", false, 10),
  dc(276, "Karun Nair", "BAT"),
  dc(187, "David Miller", "BAT", true),
  dc(23001, "Ben Duckett", "WK", true),
  dc(23020, "Pathum Nissanka", "BAT", true),
  dc(23063, "Sahil Parakh", "BAT"),
  dc(3764, "Prithvi Shaw", "BAT"),
  dc(33333, "Abishek Porel", "WK"),
  dc(20631, "Tristan Stubbs", "WK", true),
  dc(1113, "Axar Patel", "AR"),
  dc(20689, "Sameer Rizvi", "AR"),
  dc(20703, "Ashutosh Sharma", "AR"),
  dc(22053, "Vipraj Nigam", "AR"),
  dc(5811, "Ajay Mandal", "AR"),
  dc(22252, "Tripurana Vijay", "AR"),
  dc(22259, "Madhav Tiwari", "AR"),
  dc(23005, "Auqib Dar", "AR"),
  dc(2738, "Nitish Rana", "AR"),
  dc(490, "Mitchell Starc", "BOWL", true),
  dc(3831, "T. Natarajan", "BOWL"),
  dc(5622, "Mukesh Kumar", "BOWL"),
  dc(817, "Dushmantha Chameera", "BOWL", true),
  dc(3746, "Lungisani Ngidi", "BOWL", true),
  dc(1616, "Kyle Jamieson", "BOWL", true),
  dc(261, "Kuldeep Yadav", "BOWL"),

  // ── Gujarat Titans ───────────────────────────────────────────────────────
  gt(3761, "Shubman Gill", "BAT"),
  gt(509, "Jos Buttler", "WK", true, 10.5),
  gt(20694, "Kumar Kushagra", "WK"),
  gt(10788, "Anuj Rawat", "WK"),
  gt(3770, "Tom Banton", "WK", true),
  gt(3027, "Glenn Phillips", "BAT", true),
  gt(5615, "Nishant Sindhu", "AR"),
  gt(2973, "Washington Sundar", "AR"),
  gt(20599, "Mohd. Arshad Khan", "AR"),
  gt(7123, "Sai Kishore", "AR"),
  gt(1740, "Jayant Yadav", "AR"),
  gt(1075, "Jason Holder", "AR", true),
  gt(20592, "Sai Sudharsan", "AR"),
  gt(7779, "Shahrukh Khan", "AR"),
  gt(1664, "Kagiso Rabada", "BOWL", true),
  gt(3840, "Mohammed Siraj", "BOWL"),
  gt(5105, "Prasidh Krishna", "BOWL"),
  gt(20692, "Manav Suthar", "BOWL"),
  gt(1094, "Gurnoor Singh Brar", "BOWL"),
  gt(38, "Ishant Sharma", "BOWL"),
  gt(20584, "Ashok Sharma", "BOWL"),
  gt(5438, "Prithvi Raj Yarra", "BOWL"),
  gt(20721, "Luke Wood", "BOWL", true),
  gt(1749, "Rahul Tewatia", "BOWL"),
  gt(2885, "Rashid Khan", "BOWL", true, 9),

  // ── Kolkata Knight Riders ────────────────────────────────────────────────
  kkr(135, "Ajinkya Rahane", "BAT"),
  kkr(3830, "Rinku Singh", "BAT"),
  kkr(20690, "Angkrish Raghuvanshi", "BAT"),
  kkr(123, "Manish Pandey", "BAT"),
  kkr(5602, "Cameron Green", "BAT", true),
  kkr(3020, "Finn Allen", "WK", true),
  kkr(23013, "Tejasvi Singh", "WK"),
  kkr(3838, "Rahul Tripathi", "BAT"),
  kkr(1619, "Tim Seifert", "WK", true),
  kkr(3333, "Rovman Powell", "BAT", true),
  kkr(3774, "Anukul Roy", "AR"),
  kkr(23154, "Sarthak Ranjan", "AR"),
  kkr(23177, "Daksh Kamra", "AR"),
  kkr(20684, "Rachin Ravindra", "AR", true),
  kkr(20595, "Ramandeep Singh", "AR"),
  kkr(22387, "Blessing Muzarabani", "BOWL", true),
  kkr(14859, "Vaibhav Arora", "BOWL"),
  kkr(20627, "Matheesha Pathirana", "BOWL", true),
  kkr(10059, "Kartik Tyagi", "BOWL"),
  kkr(20576, "Prashant Solanki", "BOWL"),
  kkr(14800, "Akash Deep", "BOWL"),
  kkr(20626, "Harshit Rana", "BOWL"),
  kkr(15154, "Umran Malik", "BOWL"),
  kkr(203, "Sunil Narine", "BOWL", true, 9.5),
  kkr(5432, "Varun Chakaravarthy", "BOWL"),

  // ── Lucknow Super Giants ─────────────────────────────────────────────────
  lsg(2972, "Rishabh Pant", "WK", false, 9.5),
  lsg(1667, "Aiden Markram", "BAT", true),
  lsg(5434, "Himmat Singh", "BAT"),
  lsg(22375, "Matthew Breetzke", "BAT", true),
  lsg(23010, "Mukul Choudhary", "WK"),
  lsg(23035, "Akshat Raghuwanshi", "BAT"),
  lsg(22372, "Josh Inglis", "WK", true),
  lsg(1703, "Nicholas Pooran", "WK", true),
  lsg(221, "Mitchell Marsh", "AR", true),
  lsg(19352, "Abdul Samad", "AR"),
  lsg(13803, "Shahbaz Ahamad", "AR"),
  lsg(20691, "Arshin Kulkarni", "AR"),
  lsg(3082, "Wanindu Hasaranga", "AR", true),
  lsg(20586, "Ayush Badoni", "AR"),
  lsg(94, "Mohammad Shami", "BOWL"),
  lsg(1561, "Avesh Khan", "BOWL"),
  lsg(7119, "M. Siddharth", "BOWL"),
  lsg(5847, "Digvesh Singh", "BOWL"),
  lsg(12585, "Akash Singh", "BOWL"),
  lsg(22097, "Prince Yadav", "BOWL"),
  lsg(10244, "Arjun Tendulkar", "BOWL"),
  lsg(5433, "Anrich Nortje", "BOWL", true),
  lsg(23015, "Naman Tiwari", "BOWL"),
  lsg(20585, "Mayank Yadav", "BOWL"),
  lsg(4952, "Mohsin Khan", "BOWL"),

  // ── Mumbai Indians ───────────────────────────────────────────────────────
  mi(107, "Rohit Sharma", "BAT", false, 9.5),
  mi(108, "Surya Kumar Yadav", "BAT"),
  mi(20707, "Robin Minz", "WK"),
  mi(5396, "Sherfane Rutherford", "BAT", true),
  mi(22003, "Ryan Rickelton", "WK", true),
  mi(834, "Quinton de Kock", "WK", true),
  mi(23031, "Danish Malewar", "BAT"),
  mi(20594, "N. Tilak Varma", "BAT"),
  mi(2740, "Hardik Pandya", "AR", false, 10),
  mi(20701, "Naman Dhir", "AR"),
  mi(1903, "Mitchell Santner", "AR", true),
  mi(20601, "Raj Angad Bawa", "AR"),
  mi(23108, "Atharva Ankolekar", "AR"),
  mi(23038, "Mayank Rawat", "AR"),
  mi(20680, "Corbin Bosch", "AR", true),
  mi(5629, "Will Jacks", "AR", true),
  mi(1745, "Shardul Thakur", "AR"),
  mi(969, "Trent Boult", "BOWL", true),
  mi(4951, "Mayank Markande", "BOWL"),
  mi(140, "Deepak Chahar", "BOWL"),
  mi(22030, "Ashwani Kumar", "BOWL"),
  mi(22379, "Raghu Sharma", "BOWL"),
  mi(23045, "Mohammad Izhar", "BOWL"),
  mi(20725, "Allah Ghazanfar", "BOWL", true),
  mi(1124, "Jasprit Bumrah", "BOWL"),

  // ── Punjab Kings ─────────────────────────────────────────────────────────
  pbks(1563, "Shreyas Iyer", "BAT", false, 11),
  pbks(5859, "Nehal Wadhera", "BAT"),
  pbks(4305, "Vishnu Vinod", "WK"),
  pbks(22019, "Harnoor Pannu", "BAT"),
  pbks(22145, "Pyla Avinash", "BAT"),
  pbks(5436, "Prabhsimran Singh", "WK"),
  pbks(3261, "Shashank Singh", "BAT"),
  pbks(964, "Marcus Stoinis", "AR", true),
  pbks(5441, "Harpreet Brar", "AR"),
  pbks(17068, "Marco Jansen", "AR", true),
  pbks(20685, "Azmatullah Omarzai", "AR", true),
  pbks(22052, "Priyansh Arya", "AR"),
  pbks(22085, "Musheer Khan", "AR"),
  pbks(20683, "Suryansh Shedge", "AR"),
  pbks(22380, "Mitch Owen", "AR", true),
  pbks(23052, "Cooper Connolly", "AR", true),
  pbks(1478, "Ben Dwarshuis", "AR", true),
  pbks(1095, "Dasun Shanaka", "AR", true),
  pbks(4698, "Arshdeep Singh", "BOWL", false, 9),
  pbks(111, "Yuzvendra Chahal", "BOWL", false, 8.5),
  pbks(1097, "Vyshak Vijaykumar", "BOWL"),
  pbks(5624, "Yash Thakur", "BOWL"),
  pbks(22112, "Xavier Bartlett", "BOWL", true),
  pbks(3188, "Pravin Dubey", "BOWL"),
  pbks(23088, "Vishal Nishad", "BOWL"),
  pbks(3729, "Lockie Ferguson", "BOWL", true),

  // ── Rajasthan Royals ─────────────────────────────────────────────────────
  rr(4445, "Riyan Parag", "BAT"),
  rr(20688, "Shubham Dubey", "BAT"),
  rr(22203, "Vaibhav Suryavanshi", "BAT"),
  rr(5652, "Donovan Ferreira", "WK", true),
  rr(22383, "Lhuan-dre Pretorius", "BAT", true),
  rr(23044, "Ravi Singh", "WK"),
  rr(23034, "Aman Rao Perala", "BAT"),
  rr(1705, "Shimron Hetmyer", "BAT", true),
  rr(13538, "Yashasvi Jaiswal", "BAT", false, 10.5),
  rr(20620, "Dhruv Jurel", "WK"),
  rr(10842, "Yudhvir Singh Charak", "AR"),
  rr(9, "Ravindra Jadeja", "AR", false, 9.5),
  rr(3502, "Jofra Archer", "BOWL", true),
  rr(3257, "Tushar Deshpande", "BOWL"),
  rr(20724, "Kwena Maphaka", "BOWL", true),
  rr(19351, "Ravi Bishnoi", "BOWL"),
  rr(20695, "Sushant Mishra", "BOWL"),
  rr(23016, "Yash Raj Punja", "BOWL"),
  rr(22266, "Vignesh Puthur", "BOWL"),
  rr(23164, "Brijesh Sharma", "BOWL"),
  rr(434, "Adam Milne", "BOWL", true),
  rr(20616, "Kuldeep Sen", "BOWL"),
  rr(1112, "Sandeep Sharma", "BOWL"),
  rr(20716, "Nandre Burger", "BOWL", true),

  // ── Royal Challengers Bengaluru ──────────────────────────────────────────
  rcb(5471, "Rajat Patidar", "BAT"),
  rcb(5430, "Devdutt Padikkal", "BAT"),
  rcb(164, "Virat Kohli", "BAT", false, 11),
  rcb(5606, "Phil Salt", "WK", true),
  rcb(3185, "Jitesh Sharma", "WK"),
  rcb(23023, "Jordan Cox", "WK", true),
  rcb(3183, "Krunal Pandya", "AR"),
  rcb(3180, "Swapnil Singh", "AR"),
  rcb(4524, "Tim David", "AR", true),
  rcb(20609, "Romario Shepherd", "AR", true),
  rcb(22074, "Jacob Bethell", "AR", true),
  rcb(8540, "Venkatesh Iyer", "AR"),
  rcb(23036, "Satvik Deswal", "AR"),
  rcb(23040, "Mangesh Yadav", "AR"),
  rcb(20624, "Vicky Ostwal", "AR"),
  rcb(23150, "Vihaan Malhotra", "AR"),
  rcb(23168, "Kanishk Chouhan", "AR"),
  rcb(857, "Josh Hazlewood", "BOWL", true),
  rcb(20577, "Rasikh Dar", "BOWL"),
  rcb(5668, "Suyash Sharma", "BOWL"),
  rcb(116, "Bhuvneshwar Kumar", "BOWL"),
  rcb(20700, "Nuwan Thushara", "BOWL", true),
  rcb(22136, "Abhinandan Singh", "BOWL"),
  rcb(23003, "Jacob Duffy", "BOWL", true),
  rcb(20591, "Yash Dayal", "BOWL"),

  // ── Sunrisers Hyderabad ──────────────────────────────────────────────────
  srh(2975, "Ishan Kishan", "WK"),
  srh(22082, "Aniket Verma", "BAT"),
  srh(22378, "Smaran Ravichandran", "BAT"),
  srh(23041, "Salil Arora", "WK"),
  srh(3869, "Heinrich Klaasen", "WK", true),
  srh(1020, "Travis Head", "BAT", true),
  srh(157, "Harshal Patel", "AR"),
  srh(22077, "Kamindu Mendis", "AR", true),
  srh(22381, "Harsh Dubey", "AR"),
  srh(22075, "Brydon Carse", "AR", true),
  srh(23006, "Shivang Kumar", "AR"),
  srh(23132, "Krains Fuletra", "AR"),
  srh(3644, "Liam Livingstone", "AR", true),
  srh(23200, "Jack Edwards", "AR", true),
  srh(3760, "Abhishek Sharma", "AR"),
  srh(5711, "Nitish Kumar Reddy", "AR"),
  srh(488, "Pat Cummins", "BOWL", true),
  srh(22007, "Zeeshan Ansari", "BOWL"),
  srh(86, "Jaydev Unadkat", "BOWL"),
  srh(22228, "Eshan Malinga", "BOWL", true),
  srh(20717, "Sakib Hussain", "BOWL"),
  srh(23048, "Onkar Tarmale", "BOWL"),
  srh(23087, "Amit Kumar", "BOWL"),
  srh(23114, "Praful Hinge", "BOWL"),
  srh(3779, "Shivam Mavi", "BOWL")
];
